from angr-dep
maintainer stevenjiang1110@gmail.com

run su - angr -c "git clone https://github.com/angr/angr-dev && cd angr-dev && ./setup.sh -w -e angr"
run su - angr -c "echo 'workon angr' >> /home/angr/.bashrc"
cmd su - angr
